"""add test_master_id to tests

Revision ID: 13d8ab09fc40
Revises: 6bbb08285a28
Create Date: 2025-02-12 04:43:14.500086

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13d8ab09fc40"
down_revision: Union[str, None] = "6bbb08285a28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("test_master_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tests", "test_masters", ["test_master_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tests", type_="foreignkey")
    op.drop_column("tests", "test_master_id")
    # ### end Alembic commands ###
